---
 root_path: 'D:/Project/VAE_Related/ConVAE/'
 working_dir: '.'
# working_dir: 'D:/Project/VAE_Related/ConVAE'
 fname_dataset: 'data/em_train.csv'
# fname_dataset: 'data/em_train.smi'
 token_file: 'data/em_train.smi'
 fname_fps: 'data/em_fps.pkl'
 fname_tokenizer: '.tokenizer.pkl'
 fname_rnn_parameters: 'parameters/rnn.param'
 fname_vae_encoder_parameters: 'parameters/encoder.param'
 fname_vae_decoder_parameters: 'parameters/decoder.param'
 sampled_dir: 'sampled'
 target_sample_dir: 'target_sample'
 maxLength: 64
 batch_size: 256
 num_epoch: 1000
 lr: 5.0e-4
 threshold: 0.2


 rnn_param:
  embedding_dim: 256
  hidden_dim: 384
  num_hidden: 3

 vae_param:
  con_dims: 1
  fc_dims: [2048, 512, 128]
  latent_dim: 64
  hidden_dim: 384 #384
  num_hidden: 3
